"""Russian nuance extractor — motion verbs, verbal government, etymology, phrase families."""
from __future__ import annotations

from typing import Any

from backend.schemas.parse import CandidateObject, RelationHint

# Paired motion verbs: (unidirectional, multidirectional)
_MOTION_PAIRS: list[tuple[str, str]] = [
    ("идти",   "ходить"),
    ("ехать",  "ездить"),
    ("лететь", "летать"),
    ("плыть",  "плавать"),
    ("нести",  "носить"),
    ("вести",  "водить"),
    ("везти",  "возить"),
    ("бежать", "бегать"),
]

_MOTION_UNI: dict[str, str] = {
    u: f"unidirectional: movement in one direction at a specific moment"
    for u, _ in _MOTION_PAIRS
}
_MOTION_MULTI: dict[str, str] = {
    m: f"multidirectional: habitual, repeated, or back-and-forth movement"
    for _, m in _MOTION_PAIRS
}

_PAIR_MAP: dict[str, str] = {}
for _u, _m in _MOTION_PAIRS:
    _PAIR_MAP[_u] = _m
    _PAIR_MAP[_m] = _u

# Common verbs with non-obvious case government
_VERBAL_GOV: dict[str, tuple[str, str]] = {
    "ждать":          ("genitive",       "«ждать» governs the genitive: ждать автобуса"),
    "бояться":        ("genitive",       "«бояться» governs the genitive: бояться темноты"),
    "слушаться":      ("genitive",       "«слушаться» (obey) governs the genitive"),
    "помогать":       ("dative",         "«помогать» governs the dative: помогать другу"),
    "учить":          ("accusative",     "«учить» (teach/learn) governs the accusative"),
    "интересоваться": ("instrumental",   "«интересоваться» governs the instrumental"),
    "заниматься":     ("instrumental",   "«заниматься» governs the instrumental"),
    "пользоваться":   ("instrumental",   "«пользоваться» governs the instrumental"),
    "гордиться":      ("instrumental",   "«гордиться» governs the instrumental"),
    "руководить":     ("instrumental",   "«руководить» governs the instrumental"),
    "хотеть":         ("accusative/genitive",
                       "«хотеть» takes accusative (concrete) or genitive (abstract/partial)"),

    # ── generated by gen_verbal_government.py ──
    'желать': ('genitive', "«желать» governs the genitive: желать успеха (to wish success), желать добра (to wish well), желать счастья (to wish happiness). Contrast with accusative verbs of wanting."),
    'требовать': ('genitive', "«требовать» governs the genitive: требовать ответа (to demand an answer), требовать уважения (to demand respect). The demanded thing takes genitive."),
    'добиваться': ('genitive', "«добиваться» (impf.) governs the genitive: добиваться правды (to seek the truth), добиваться справедливости (to pursue justice). The goal takes genitive."),
    'достигать': ('genitive', "«достигать» governs the genitive: достигать цели (to reach a goal), достигать успеха (to achieve success). Compare with движение к + dative."),
    'избегать': ('genitive', "«избегать» governs the genitive: избегать опасности (to avoid danger), избегать встречи (to avoid a meeting). The avoided thing takes genitive."),
    'касаться': ('genitive', "«касаться» governs the genitive: касаться темы (to touch on a topic), это меня не касается (that doesn't concern me). Impersonal uses also take genitive."),
    'лишаться': ('genitive', "«лишаться» governs the genitive: лишаться работы (to lose one's job), лишаться сознания (to lose consciousness). The lost thing takes genitive."),
    'ожидать': ('genitive', "«ожидать» governs the genitive: ожидать автобуса (to wait for the bus), ожидать гостей (to expect guests). Synonymous with ждать + genitive."),
    'остерегаться': ('genitive', "«остерегаться» governs the genitive: остерегаться мошенников (to beware of fraudsters), остерегайся опасности (beware of danger)."),
    'стыдиться': ('genitive', "«стыдиться» governs the genitive: стыдиться своего поступка (to be ashamed of one's action), стыдиться ошибки (to be ashamed of a mistake)."),
    'жалеть': ('genitive', "«жалеть» governs the genitive: жалеть времени (to be sparing with time), жалеть денег (to begrudge money). When meaning 'to pity' it takes accusative."),
    'просить': ('genitive', "«просить» governs genitive of the thing requested: просить помощи (to ask for help), просить совета (to ask for advice). But takes accusative of the person asked."),
    'искать': ('genitive', "«искать» can govern the genitive for abstract nouns: искать правды (to seek truth), искать справедливости (to seek justice). Concrete objects take accusative."),
    'недоставать': ('genitive', "«недоставать» (impersonal) governs the genitive: ему недостаёт терпения (he lacks patience), мне недостаёт опыта (I lack experience)."),
    'заслуживать': ('genitive', "«заслуживать» governs the genitive: заслуживать уважения (to deserve respect), заслуживать внимания (to merit attention), заслуживать доверия (to be trustworthy)."),
    'придерживаться': ('genitive', "«придерживаться» governs the genitive: придерживаться правил (to adhere to rules), придерживаться диеты (to stick to a diet), придерживаться мнения (to hold an opinion)."),
    'избавиться': ('genitive', "«избавиться» governs the genitive: избавиться от привычки (to break a habit — от+gen), избавиться от долга (to free oneself from debt). Always used with от."),
    'добиться': ('genitive', "«добиться» (pf.) governs the genitive: добиться результата (to achieve a result), добиться своего (to get one's way), добиться признания (to gain recognition)."),
    'нравиться': ('dative', "«нравиться» governs the dative of the experiencer: мне нравится музыка (I like music — lit. music pleases me), ей нравится этот фильм (she likes this film). The subject is the liked thing."),
    'доверять': ('dative', "«доверять» governs the dative: доверять другу (to trust a friend), нельзя доверять незнакомцу (you can't trust a stranger). The trusted person takes dative."),
    'звонить': ('dative', "«звонить» governs the dative: звонить другу (to call a friend), позвоните мне (call me). The person called takes dative, unlike English where the number/person is direct object."),
    'отвечать': ('dative', "«отвечать» governs the dative: отвечать другу (to answer a friend), отвечать на вопрос (to answer a question — на+acc for the question itself)."),
    'мешать': ('dative', "«мешать» governs the dative: мешать работе (to interfere with work), не мешай мне (don't bother me), мешать другим (to disturb others). Can also take infinitive."),
    'верить': ('dative', "«верить» governs the dative: верить другу (to believe a friend), верить в Бога (to believe in God — в+acc), верить слухам (to believe rumours). Person or word believed takes dative."),
    'завидовать': ('dative', "«завидовать» governs the dative: завидовать соседу (to envy a neighbour), завидую вашему таланту (I envy your talent). The envied person/thing takes dative."),
    'угрожать': ('dative', "«угрожать» governs the dative: угрожать противнику (to threaten an opponent), это угрожает миру (this threatens peace). The threatened entity takes dative."),
    'подражать': ('dative', "«подражать» governs the dative: подражать учителю (to imitate a teacher), подражать великим (to emulate the greats). The imitated person/style takes dative."),
    'соответствовать': ('dative', "«соответствовать» governs the dative: соответствовать стандартам (to meet standards), не соответствует действительности (doesn't correspond to reality)."),
    'удивляться': ('dative', "«удивляться» governs the dative: удивляться таланту (to be amazed by talent), удивляюсь твоей смелости (I marvel at your courage). What surprises takes dative."),
    'радоваться': ('dative', "«радоваться» governs the dative: радоваться успеху (to rejoice at success), рад встрече (glad about the meeting — rад+dative). The occasion of joy takes dative."),
    'сочувствовать': ('dative', "«сочувствовать» governs the dative: сочувствовать другу (to sympathize with a friend), сочувствую вашей утрате (I sympathize with your loss)."),
    'следовать': ('dative', "«следовать» governs the dative: следовать совету (to follow advice), следовать примеру (to follow an example), следовать правилам (to follow rules). The thing followed takes dative."),
    'уступать': ('dative', "«уступать» governs the dative: уступать место (to give up one's seat — with acc of what is given up), уступать давлению (to yield to pressure)."),
    'казаться': ('dative', "«казаться» governs the dative of the perceiver: мне кажется (it seems to me), ей казалось (it seemed to her). The subject is the apparent thing; the perceiver takes dative."),
    'сниться': ('dative', "«сниться» governs the dative of the dreamer: мне снился сон (I had a dream — lit. a dream dreamed to me), тебе снится (you're dreaming). Subject is the dream content."),
    'принадлежать': ('dative', "«принадлежать» governs the dative: книга принадлежит мне (the book belongs to me), это принадлежит истории (this belongs to history)."),
    'аплодировать': ('dative', "«аплодировать» governs the dative: аплодировать актёру (to applaud the actor), зал аплодировал выступлению (the hall applauded the performance)."),
    'управлять': ('instrumental', "«управлять» governs the instrumental: управлять автомобилем (to drive a car), управлять страной (to run a country), управлять самолётом (to pilot a plane). Control takes instrumental."),
    'владеть': ('instrumental', "«владеть» governs the instrumental: владеть языком (to command a language), владеть собственностью (to own property), хорошо владеет ситуацией (has good command of the situation)."),
    'дорожить': ('instrumental', "«дорожить» governs the instrumental: дорожить дружбой (to cherish a friendship), дорожить временем (to value one's time), дорожим своей репутацией (we value our reputation)."),
    'восхищаться': ('instrumental', "«восхищаться» governs the instrumental: восхищаться природой (to admire nature), восхищаться мастерством (to be in awe of skill), восхищаюсь вашей работой (I admire your work)."),
    'увлекаться': ('instrumental', "«увлекаться» governs the instrumental: увлекаться музыкой (to be enthusiastic about music), увлекаться спортом (to be into sport), давно увлекается историей (has long been into history)."),
    'жертвовать': ('instrumental', "«жертвовать» governs the instrumental: жертвовать временем (to sacrifice one's time), жертвовать собой (to sacrifice oneself), жертвовать принципами (to compromise principles)."),
    'рисковать': ('instrumental', "«рисковать» governs the instrumental: рисковать жизнью (to risk one's life), рисковать здоровьем (to risk one's health), не стоит рисковать карьерой (don't risk your career)."),
    'делиться': ('instrumental', "«делиться» governs the instrumental: делиться опытом (to share experience), делиться новостями (to share news), поделиться мыслями (to share thoughts)."),
    'хвастаться': ('instrumental', "«хвастаться» governs the instrumental: хвастаться успехами (to boast about achievements), не хвастайся богатством (don't show off your wealth)."),
    'обладать': ('instrumental', "«обладать» governs the instrumental: обладать талантом (to possess talent), обладать правом (to have a right), обладает сильным характером (has a strong character)."),
    'являться': ('instrumental', "«являться» governs the instrumental in formal Russian: является гражданином (is a citizen), является причиной (is the cause). Used in bureaucratic/official style where быть is avoided."),
    'становиться': ('instrumental', "«становиться» governs the instrumental: становиться врачом (to become a doctor), стала известной (became famous), становится лучше (is getting better — short adj. also possible)."),
    'оказываться': ('instrumental', "«оказываться» governs the instrumental: оказаться правым (to turn out to be right), оказался отличным специалистом (turned out to be an excellent specialist)."),
    'считаться': ('instrumental', "«считаться» governs the instrumental: считаться экспертом (to be considered an expert), считается устаревшим (is considered outdated). Passive voice of 'to consider'."),
    'притворяться': ('instrumental', "«притворяться» governs the instrumental: притворяться больным (to pretend to be ill), притворялся другом (pretended to be a friend). What one pretends to be takes instrumental."),
    'любоваться': ('instrumental', "«любоваться» governs the instrumental: любоваться закатом (to admire a sunset), любоваться пейзажем (to enjoy the view), любовались звёздами (were gazing at the stars)."),
    'говорить о': ('prepositional+о', "«говорить о» governs the prepositional with preposition о: говорить о проблеме (to talk about a problem), говорить о будущем (to speak about the future). О+prepositional for topics."),
    'думать о': ('prepositional+о', "«думать о» governs the prepositional: думать о работе (to think about work), думаю о тебе (I'm thinking of you), что вы думаете об этом? (what do you think about this? — об before vowels)."),
    'мечтать о': ('prepositional+о', "«мечтать о» governs the prepositional: мечтать о поездке (to dream of a trip), мечтает о карьере (dreams of a career). Distinguish from мечтать + infinitive (to dream of doing)."),
    'заботиться о': ('prepositional+о', "«заботиться о» governs the prepositional: заботиться о детях (to care for children), заботиться о здоровье (to look after one's health). Care directed at person/thing takes о+prep."),
    'беспокоиться о': ('prepositional+о', "«беспокоиться о» governs the prepositional: беспокоиться о здоровье (to worry about health), беспокоюсь о тебе (I worry about you). Also used with за+acc: беспокоиться за детей."),
    'договариваться о': ('prepositional+о', "«договариваться о» governs the prepositional: договориться о встрече (to agree on a meeting), договариваться о цене (to negotiate a price). The agreed-upon thing takes о+prep."),
    'спорить о': ('prepositional+о', "«спорить о» governs the prepositional: спорить о политике (to argue about politics), о чём вы спорите? (what are you arguing about?). Topic of dispute takes о+prepositional."),
    'вспоминать о': ('prepositional+о', "«вспоминать о» governs the prepositional: вспоминать о детстве (to recall childhood), часто вспоминаю о вас (I often think of you). Also + accusative when emphasizing the specific memory."),
    'сообщать о': ('prepositional+о', "«сообщать о» governs the prepositional: сообщать о событии (to report an event), СМИ сообщают о кризисе (the media report on a crisis). Topic reported takes о+prep."),
    'узнавать о': ('prepositional+о', "«узнавать о» governs the prepositional: узнавать о новостях (to learn the news), узнал о произошедшем (found out about what happened). Compare: узнать человека (to recognize someone — acc)."),
    'объяснять': ('accusative+dative', "«объяснять» takes dative of the recipient and accusative of what is explained: объяснять ученику (dative) задачу (accusative) — to explain a problem to a student."),
    'давать': ('accusative+dative', "«давать» takes dative of recipient and accusative of thing given: давать другу (dative) книгу (accusative) — to give a friend a book. Standard double-object pattern."),
    'показывать': ('accusative+dative', "«показывать» takes dative of person shown and accusative of thing shown: показывать гостям (dative) город (accusative) — to show guests the city."),
    'спрашивать': ('accusative+dative', "«спрашивать» takes accusative of person asked and о+prepositional of topic: спрашивать учителя (acc) о задании (о+prep) — to ask the teacher about the assignment."),
    'лишать': ('genitive+dative', "«лишать» takes accusative of the person deprived and genitive of what is taken: лишать студента (acc) стипендии (gen) — to deprive a student of their scholarship."),
    'дышать': ('instrumental', "«дышать» in medical/poetic contexts governs the instrumental: дышать морским воздухом (to breathe sea air), дышать полной грудью (to breathe deeply/fully). Colloquial use with нечем дышать (nothing to breathe with)."),
    'пить': ('accusative/genitive', "«пить» governs accusative (specific/whole): пить воду (to drink water). Genitive signals partial quantity: выпить воды (to drink some water), хочу молока (I want some milk — ellipted 'drink/have')."),
    'есть': ('accusative/genitive', "«есть» (to eat) governs accusative for specific/whole objects: есть яблоко (to eat an apple). Genitive signals partitive: съесть хлеба (to eat some bread), хочу супа (I want some soup)."),
    'уважать': ('accusative', "«уважать» governs the accusative: уважать старших (to respect one's elders), уважаем ваш выбор (we respect your choice). Learners sometimes expect genitive; accusative is correct."),
    'ненавидеть': ('accusative', "«ненавидеть» governs the accusative: ненавидеть ложь (to hate lying), ненавижу понедельники (I hate Mondays). Accusative throughout; no genitive alternation."),
    'помнить': ('accusative', "«помнить» governs the accusative: помнить урок (to remember a lesson), я помню тебя (I remember you). The remembered thing takes accusative, not genitive as beginners sometimes assume."),
    'любить': ('accusative', "«любить» governs the accusative: любить родину (to love one's homeland), люблю музыку (I love music). Pure accusative; no case alternation."),
    'служить': ('dative', "«служить» in the sense 'to serve someone' governs the dative: служить народу (to serve the people), служить Родине (to serve one's country). In the sense 'to serve as' it takes instrumental."),
    'писать': ('dative', "«писать» governs dative of the recipient: писать другу (to write to a friend), напишите нам (write to us). The text/content takes accusative: писать письмо другу (to write a letter to a friend)."),
    'учиться': ('dative', "«учиться» governs dative of the subject studied: учиться музыке (to study music), учиться у мастера (to learn from a master — у+gen). Contrast учить + accusative."),
    'читать': ('accusative', "«читать» governs the accusative: читать книгу (to read a book), читать лекцию (to give a lecture). When meaning 'to read to someone', recipient takes dative: читать детям сказку (to read children a fairy tale)."),
    'оставаться': ('instrumental', "«оставаться» in the sense 'to remain as' governs the instrumental: оставаться другом (to remain a friend), остался лидером (remained the leader). Contrast with intransitive оставаться (to stay)."),
    'работать': ('instrumental', "«работать» in the sense 'to work as' governs the instrumental: работать врачом (to work as a doctor), работает переводчиком (works as a translator). Occupational designation takes instrumental."),
    'быть': ('instrumental', "«быть» in the past and future tenses governs the instrumental for predicate nouns: он был студентом (he was a student), она будет врачом (she will be a doctor). Present tense omits быть in Russian."),
    'назначить': ('instrumental', "«назначить» governs the instrumental of the role/position: назначить директором (to appoint as director), его назначили министром (he was appointed minister). The new role takes instrumental."),
    'считать': ('instrumental', "«считать» (to consider) governs the instrumental: считать его другом (to consider him a friend), считаю это ошибкой (I consider this a mistake). Compare считаться + instrumental (to be considered)."),
    'выбрать': ('instrumental', "«выбрать» in the sense 'to elect/appoint as' governs the instrumental: выбрали президентом (elected as president), назначить премьером (appoint as prime minister). Role/office takes instrumental."),
    'представляться': ('instrumental', "«представляться» (to introduce oneself as / to seem) governs the instrumental: представился журналистом (introduced himself as a journalist), это мне представляется странным (this seems strange to me)."),
}


def _lemma(c: CandidateObject) -> str:
    return c.lesson_data.get("lemma", c.canonical_form)


class RussianNuanceExtractor:
    language = "ru"

    def extract_nuance(
        self,
        sentence: str,
        tokens: list[Any],
        candidates: list[CandidateObject],
        language: str,
    ) -> list[CandidateObject]:
        out: list[CandidateObject] = []
        seen: set[str] = set()
        out.extend(self._motion_verbs(candidates, seen))
        out.extend(self._verbal_government(candidates, seen))
        out.extend(self._etymology(candidates, seen))
        out.extend(self._phrase_families(tokens))
        return out

    def _motion_verbs(
        self, candidates: list[CandidateObject], seen: set[str]
    ) -> list[CandidateObject]:
        out = []
        for c in candidates:
            if c.type not in ("vocabulary", "conjugation"):
                continue
            lemma = _lemma(c)
            if lemma in _MOTION_UNI:
                direction = "unidirectional"
                desc = _MOTION_UNI[lemma]
            elif lemma in _MOTION_MULTI:
                direction = "multidirectional"
                desc = _MOTION_MULTI[lemma]
            else:
                continue
            cf = f"nuance:ru:motion_verb:{lemma}"
            if cf in seen:
                continue
            seen.add(cf)
            partner = _PAIR_MAP.get(lemma)
            hints = [RelationHint(
                relation_type="nuance_of",
                target_canonical_form=lemma,
                target_type="vocabulary",
            )]
            if partner:
                hints.append(RelationHint(
                    relation_type="motion_pair",
                    target_canonical_form=partner,
                    target_type="vocabulary",
                ))
            out.append(CandidateObject(
                canonical_form=cf,
                surface_form=c.surface_form,
                type="nuance",
                label=c.label,
                lesson_data={
                    "nuance_type": "motion_verb",
                    "explanation": (
                        f"«{lemma}» is a {direction} motion verb: {desc}. "
                        "Russian pairs motion verbs by directionality: unidirectional verbs "
                        "describe a single trip at a given moment; multidirectional verbs "
                        "describe habitual, repeated, or back-and-forth movement."
                        + (f" Its pair is «{partner}»." if partner else "")
                    ),
                    "register": "neutral",
                    "learner_level": "B1",
                    "source": "heuristic",
                    "lemma": lemma,
                    "direction_type": direction,
                    "partner_lemma": partner,
                },
                confidence=0.85,
                relation_hints=hints,
            ))
        return out

    def _verbal_government(
        self, candidates: list[CandidateObject], seen: set[str]
    ) -> list[CandidateObject]:
        out = []
        for c in candidates:
            if c.type not in ("vocabulary", "conjugation"):
                continue
            lemma = _lemma(c)
            if lemma not in _VERBAL_GOV:
                continue
            required_case, example = _VERBAL_GOV[lemma]
            cf = f"nuance:ru:verbal_government:{lemma}"
            if cf in seen:
                continue
            seen.add(cf)
            out.append(CandidateObject(
                canonical_form=cf,
                surface_form=c.surface_form,
                type="nuance",
                label=c.label,
                lesson_data={
                    "nuance_type": "verbal_government",
                    "explanation": (
                        f"{example}. "
                        "Russian verbs govern a specific case for their direct/indirect objects — "
                        "this is an inherent property of the verb, not predictable from context. "
                        f"Required case: {required_case}."
                    ),
                    "register": "neutral",
                    "learner_level": "B1",
                    "source": "heuristic",
                    "lemma": lemma,
                    "required_case": required_case,
                },
                confidence=0.85,
                relation_hints=[RelationHint(
                    relation_type="nuance_of",
                    target_canonical_form=lemma,
                    target_type="vocabulary",
                )],
            ))
        return out

    def _etymology(
        self, candidates: list[CandidateObject], seen: set[str]
    ) -> list[CandidateObject]:
        from backend.dictionary.etymology import DEFAULT_STORE
        out = []
        for c in candidates:
            if c.type != "vocabulary":
                continue
            lemma = c.lesson_data.get("lemma") or c.canonical_form
            entry = DEFAULT_STORE.get(self.language, lemma)
            if not entry:
                continue
            cf = f"nuance:{self.language}:etymology:{lemma.lower()}"
            if cf in seen:
                continue
            seen.add(cf)
            out.append(CandidateObject(
                canonical_form=cf,
                surface_form=c.surface_form,
                type="nuance",
                label=c.label,
                lesson_data={
                    "nuance_type": "etymology",
                    "explanation": entry.origin_summary,
                    "register": "neutral",
                    "learner_level": "B1",
                    "source": entry.source_type,
                    "etymology": entry.to_lesson_data(),
                },
                confidence=0.85,
                relation_hints=[RelationHint(
                    relation_type="nuance_of",
                    target_canonical_form=lemma,
                    target_type="vocabulary",
                )],
            ))
        return out

    def _phrase_families(self, tokens: list[Any]) -> list[CandidateObject]:
        from backend.dictionary.phrase_families import match_phrase_families
        def _text(tok: Any) -> str:
            return tok.text if hasattr(tok, "text") else str(tok)
        return match_phrase_families([_text(t) for t in tokens], self.language)
