"""Koine Greek plugin — dictionary-mode with morphological annotations.

BCP-47 code ``"grc"``.  Provides whitespace tokenisation backed by:

  1. A compact curated set of ~100 NT Greek headwords (always available;
     glosses tuned for Koine/NT usage, which differs from Classical Greek).
  2. A 19 000-entry Wiktionary-derived lexicon from
     ``data/lexicons/grc_lemmas.json`` (generated by ``scripts/ingest_kaikki.py``).
  3. A 797 000-entry inflection table from ``data/lexicons/grc_inflections.json``
     that maps normalised inflected forms back to their lemma keys.
  4. A 27 000-entry morphological index from ``data/lexicons/grc_morph.json``
     (generated by ``scripts/ingest_classical_morph.py`` from PROIEL CoNLL-U
     and MorphGNT; provides case, number, gender, tense, mood, voice, person
     for annotated forms).

Lookup order per token:
  curated  →  kaikki lemma  →  kaikki inflection  →  unknown.
  Morphological features overlaid from grc_morph.json when available.

Sources
────────
  grc_morph.json is derived from:
    - grc_proiel-ud-dev.conllu (PROIEL Ancient Greek; CC BY-NC-SA)
    - morphgnt_sblgnt.txt (MorphGNT; CC BY-SA 3.0, non-commercial)
  See scripts/ingest_classical_morph.py for derivation details.

Known limitations
─────────────────
  Morphological features are available for ~27 000 forms (PROIEL dev set +
  full Greek NT).  Forms outside these corpora receive dictionary-mode output
  without morphological annotations.  No complete paradigm inference is
  performed; unknown inflected forms carry a confidence_note.
"""
from __future__ import annotations

import json
import re
import unicodedata
from functools import lru_cache
from pathlib import Path
from typing import Any

from backend.core.classical_normalize import normalize_greek
from backend.schemas.language import LanguageCapabilities, NuanceCapabilities
from backend.schemas.parse import CandidateObject, CandidateSentenceResult

_DATA = Path(__file__).parents[2] / "data" / "lexicons"

# ── Sentence splitting / token cleaning ──────────────────────────────────────
_SENTENCE_RE = re.compile(r"[^.!?;\n·]+[.!?;\n·]?")
_STRIP_PUNCT = re.compile(
    r"^[.,;:!?()\[\]\"'«»—\-·;·]+"
    r"|[.,;:!?()\[\]\"'«»—\-·;·]+$"
)

# ── Transliteration ───────────────────────────────────────────────────────────
_TRANSLIT: dict[str, str] = {
    "α": "a",  "β": "b",  "γ": "g",  "δ": "d",  "ε": "e",
    "ζ": "z",  "η": "ē",  "θ": "th", "ι": "i",  "κ": "k",
    "λ": "l",  "μ": "m",  "ν": "n",  "ξ": "x",  "ο": "o",
    "π": "p",  "ρ": "r",  "σ": "s",  "ς": "s",  "τ": "t",
    "υ": "y",  "φ": "ph", "χ": "ch", "ψ": "ps", "ω": "ō",
}


def transliterate(word: str) -> str:
    """Simplified SBL-style romanisation of *word*."""
    return "".join(_TRANSLIT.get(ch, ch) for ch in normalize_greek(word))


# ── Curated overrides (Koine/NT-tuned glosses) ───────────────────────────────

_CURATED: dict[str, dict[str, str]] = {
    # Verbs
    "ειμι":       {"citation": "εἰμί",                       "gloss": "be, exist, am",                             "pos": "verb", "grammar_note": "highly irregular; 2sg εἶ, 3sg ἐστίν, 1pl ἐσμέν, 3pl εἰσίν"},
    "λεγω":       {"citation": "λέγω",                       "gloss": "say, speak, tell",                           "pos": "verb", "grammar_note": "1st aorist εἶπον (suppletive); fut. ἐρῶ"},
    "εχω":        {"citation": "ἔχω",                        "gloss": "have, hold, possess",                        "pos": "verb", "grammar_note": "2nd aorist ἔσχον; fut. ἕξω"},
    "γινομαι":    {"citation": "γίνομαι",                    "gloss": "become, be, happen, come to be",             "pos": "verb", "grammar_note": "deponent; 2nd aorist ἐγενόμην; pf. γέγονα"},
    "ερχομαι":    {"citation": "ἔρχομαι",                    "gloss": "come, go",                                   "pos": "verb", "grammar_note": "highly irregular; 2nd aorist ἦλθον; fut. ἐλεύσομαι"},
    "ποιεω":      {"citation": "ποιέω",                      "gloss": "do, make, cause",                            "pos": "verb", "grammar_note": "contracted -έω verb; aorist ἐποίησα"},
    "ακουω":      {"citation": "ἀκούω",                      "gloss": "hear, listen to",                            "pos": "verb", "grammar_note": "aorist ἤκουσα; gen. of person, acc. of thing"},
    "βλεπω":      {"citation": "βλέπω",                      "gloss": "see, look at",                               "pos": "verb", "grammar_note": "aorist ἔβλεψα"},
    "οραω":       {"citation": "ὁράω",                       "gloss": "see, perceive",                              "pos": "verb", "grammar_note": "suppletive: pres. ὁράω, aorist εἶδον, pf. ἑώρακα"},
    "γινωσκω":    {"citation": "γινώσκω",                    "gloss": "know, come to know, understand",             "pos": "verb", "grammar_note": "2nd aorist ἔγνων; pf. ἔγνωκα"},
    "πιστευω":    {"citation": "πιστεύω",                    "gloss": "believe, trust, have faith in",              "pos": "verb", "grammar_note": "takes dative or εἰς + accusative"},
    "λαμβανω":    {"citation": "λαμβάνω",                    "gloss": "take, receive",                              "pos": "verb", "grammar_note": "2nd aorist ἔλαβον; pf. εἴληφα"},
    "αγαπαω":     {"citation": "ἀγαπάω",                     "gloss": "love (unconditionally), regard highly",      "pos": "verb", "grammar_note": "contracted -άω verb; aorist ἠγάπησα"},
    "αποστελλω":  {"citation": "ἀποστέλλω",                  "gloss": "send (out), commission",                     "pos": "verb", "grammar_note": "compound of ἀπό + στέλλω; aorist ἀπέστειλα"},
    "εισερχομαι": {"citation": "εἰσέρχομαι",                 "gloss": "enter, go into",                             "pos": "verb", "grammar_note": "compound deponent; 2nd aorist εἰσῆλθον"},
    "εξερχομαι":  {"citation": "ἐξέρχομαι",                  "gloss": "go out, come out",                           "pos": "verb", "grammar_note": "compound deponent; 2nd aorist ἐξῆλθον"},
    "λυω":        {"citation": "λύω",                        "gloss": "loose, release, dissolve",                   "pos": "verb", "grammar_note": "aorist ἔλυσα; pf. λέλυκα; standard paradigm verb"},
    "γραφω":      {"citation": "γράφω",                      "gloss": "write, record",                              "pos": "verb", "grammar_note": "aorist ἔγραψα; pf. γέγραφα"},
    "ζαω":        {"citation": "ζάω",                        "gloss": "live, be alive",                             "pos": "verb", "grammar_note": "contracted -άω verb; fut. ζήσω"},
    "θελω":       {"citation": "θέλω",                       "gloss": "will, wish, want, desire",                   "pos": "verb", "grammar_note": "aorist ἠθέλησα"},
    "δυναμαι":    {"citation": "δύναμαι",                    "gloss": "be able, can, have power",                   "pos": "verb", "grammar_note": "deponent; always middle/passive forms"},
    "απολλυμι":   {"citation": "ἀπόλλυμι",                   "gloss": "destroy; (mid.) perish, be lost",            "pos": "verb", "grammar_note": "compound of ἀπό + ὄλλυμι; 2nd aorist ἀπωλόμην (mid.)"},
    # Nouns
    "θεος":       {"citation": "θεός, θεοῦ, ὁ",             "gloss": "God, god, deity",                            "pos": "noun", "grammar_note": "2nd declension masculine"},
    "κυριος":     {"citation": "κύριος, κυρίου, ὁ",          "gloss": "Lord, master, owner",                        "pos": "noun", "grammar_note": "2nd declension masculine"},
    "λογος":      {"citation": "λόγος, λόγου, ὁ",            "gloss": "word, message, reason, account",             "pos": "noun", "grammar_note": "2nd declension masculine; ἐν ἀρχῇ ἦν ὁ λόγος"},
    "ανθρωπος":   {"citation": "ἄνθρωπος, ἀνθρώπου, ὁ",      "gloss": "person, human being, man",                   "pos": "noun", "grammar_note": "2nd declension masculine"},
    "υιος":       {"citation": "υἱός, υἱοῦ, ὁ",             "gloss": "son",                                        "pos": "noun", "grammar_note": "2nd declension masculine"},
    "πατηρ":      {"citation": "πατήρ, πατρός, ὁ",           "gloss": "father",                                     "pos": "noun", "grammar_note": "3rd declension masculine; voc. πάτερ"},
    "αρχη":       {"citation": "ἀρχή, ἀρχῆς, ἡ",            "gloss": "beginning, origin, rule, authority",         "pos": "noun", "grammar_note": "1st declension feminine"},
    "ημερα":      {"citation": "ἡμέρα, ἡμέρας, ἡ",          "gloss": "day",                                        "pos": "noun", "grammar_note": "1st declension feminine"},
    "οικος":      {"citation": "οἶκος, οἴκου, ὁ",           "gloss": "house, home, household",                     "pos": "noun", "grammar_note": "2nd declension masculine"},
    "καρδια":     {"citation": "καρδία, καρδίας, ἡ",         "gloss": "heart (physical and metaphorical)",          "pos": "noun", "grammar_note": "1st declension feminine"},
    "κοσμος":     {"citation": "κόσμος, κόσμου, ὁ",          "gloss": "world, universe, order",                     "pos": "noun", "grammar_note": "2nd declension masculine"},
    "ζωη":        {"citation": "ζωή, ζωῆς, ἡ",              "gloss": "life",                                       "pos": "noun", "grammar_note": "1st declension feminine; ζωὴ αἰώνιος = eternal life"},
    "αιων":       {"citation": "αἰών, αἰῶνος, ὁ",           "gloss": "age, eternity; εἰς τὸν αἰῶνα = forever",    "pos": "noun", "grammar_note": "3rd declension masculine"},
    "δουλος":     {"citation": "δοῦλος, δούλου, ὁ",          "gloss": "slave, servant",                             "pos": "noun", "grammar_note": "2nd declension masculine"},
    "αδελφος":    {"citation": "ἀδελφός, ἀδελφοῦ, ὁ",        "gloss": "brother",                                    "pos": "noun", "grammar_note": "2nd declension masculine; fem. ἀδελφή"},
    "αδελφη":     {"citation": "ἀδελφή, ἀδελφῆς, ἡ",         "gloss": "sister",                                     "pos": "noun", "grammar_note": "1st declension feminine"},
    "εκκλησια":   {"citation": "ἐκκλησία, ἐκκλησίας, ἡ",     "gloss": "assembly, church, congregation",             "pos": "noun", "grammar_note": "1st declension feminine"},
    "γη":         {"citation": "γῆ, γῆς, ἡ",                "gloss": "earth, land, soil",                          "pos": "noun", "grammar_note": "1st declension feminine"},
    "φωνη":       {"citation": "φωνή, φωνῆς, ἡ",             "gloss": "voice, sound",                               "pos": "noun", "grammar_note": "1st declension feminine"},
    "ονομα":      {"citation": "ὄνομα, ὀνόματος, τό",         "gloss": "name",                                       "pos": "noun", "grammar_note": "3rd declension neuter"},
    "πνευμα":     {"citation": "πνεῦμα, πνεύματος, τό",       "gloss": "spirit, wind, breath",                       "pos": "noun", "grammar_note": "3rd declension neuter; τὸ ἅγιον πνεῦμα = the Holy Spirit"},
    "αιμα":       {"citation": "αἷμα, αἵματος, τό",           "gloss": "blood",                                      "pos": "noun", "grammar_note": "3rd declension neuter"},
    "σωμα":       {"citation": "σῶμα, σώματος, τό",           "gloss": "body",                                       "pos": "noun", "grammar_note": "3rd declension neuter"},
    "πιστις":     {"citation": "πίστις, πίστεως, ἡ",          "gloss": "faith, belief, trust",                       "pos": "noun", "grammar_note": "3rd declension feminine (i-stem)"},
    "αγαπη":      {"citation": "ἀγάπη, ἀγάπης, ἡ",           "gloss": "love (unconditional, self-giving)",          "pos": "noun", "grammar_note": "1st declension feminine"},
    "χαρα":       {"citation": "χαρά, χαρᾶς, ἡ",             "gloss": "joy, gladness",                              "pos": "noun", "grammar_note": "1st declension feminine"},
    "χαρις":      {"citation": "χάρις, χάριτος, ἡ",           "gloss": "grace, favour, thankfulness",                "pos": "noun", "grammar_note": "3rd declension feminine"},
    "ειρηνη":     {"citation": "εἰρήνη, εἰρήνης, ἡ",          "gloss": "peace",                                      "pos": "noun", "grammar_note": "1st declension feminine"},
    "αληθεια":    {"citation": "ἀλήθεια, ἀληθείας, ἡ",        "gloss": "truth",                                      "pos": "noun", "grammar_note": "1st declension feminine"},
    "νομος":      {"citation": "νόμος, νόμου, ὁ",             "gloss": "law, Torah",                                 "pos": "noun", "grammar_note": "2nd declension masculine"},
    "βασιλεια":   {"citation": "βασιλεία, βασιλείας, ἡ",      "gloss": "kingdom, reign",                             "pos": "noun", "grammar_note": "1st declension feminine; ἡ βασιλεία τοῦ θεοῦ"},
    "αμαρτια":    {"citation": "ἁμαρτία, ἁμαρτίας, ἡ",        "gloss": "sin, error (missing the mark)",              "pos": "noun", "grammar_note": "1st declension feminine"},
    "εργον":      {"citation": "ἔργον, ἔργου, τό",            "gloss": "work, deed, action",                         "pos": "noun", "grammar_note": "2nd declension neuter"},
    "δικαιοσυνη": {"citation": "δικαιοσύνη, δικαιοσύνης, ἡ",  "gloss": "righteousness, justice",                     "pos": "noun", "grammar_note": "1st declension feminine"},
    # Pronouns
    "εγω":        {"citation": "ἐγώ",                        "gloss": "I",                                          "pos": "pron", "grammar_note": "1st person singular; gen. ἐμοῦ / μου"},
    "συ":         {"citation": "σύ",                         "gloss": "you (singular)",                             "pos": "pron", "grammar_note": "2nd person singular; gen. σοῦ / σου"},
    "αυτος":      {"citation": "αὐτός, αὐτή, αὐτό",          "gloss": "he/she/it; same, himself (intensive)",       "pos": "pron", "grammar_note": "also used as 3rd person pronoun"},
    "ουτος":      {"citation": "οὗτος, αὕτη, τοῦτο",          "gloss": "this (near demonstrative)",                  "pos": "pron", "grammar_note": "demonstrative pronoun/adjective"},
    "εκεινος":    {"citation": "ἐκεῖνος, ἐκείνη, ἐκεῖνο",     "gloss": "that (far demonstrative)",                   "pos": "pron", "grammar_note": "demonstrative pronoun/adjective"},
    "ος":         {"citation": "ὅς, ἥ, ὅ",                  "gloss": "who, which, that (relative pronoun)",        "pos": "pron", "grammar_note": "declines like article with rough breathing"},
    "τις":        {"citation": "τίς, τί",                    "gloss": "who? what? (interrogative)",                 "pos": "pron", "grammar_note": "3rd declension; accent marks interrogative vs. enclitic τις"},
    # Article
    "ο":          {"citation": "ὁ, ἡ, τό",                  "gloss": "the (definite article)",                     "pos": "det",  "grammar_note": "3 genders, 2 numbers, 5 cases; no vocative"},
    # Prepositions
    "εν":         {"citation": "ἐν (+ dat.)",                "gloss": "in, on, among, by means of",                 "pos": "prep", "grammar_note": "governs dative"},
    "εις":        {"citation": "εἰς (+ acc.)",               "gloss": "into, to, toward, for (purpose)",            "pos": "prep", "grammar_note": "governs accusative"},
    "εκ":         {"citation": "ἐκ / ἐξ (+ gen.)",           "gloss": "out of, from",                               "pos": "prep", "grammar_note": "ἐκ before consonants, ἐξ before vowels"},
    "απο":        {"citation": "ἀπό (+ gen.)",               "gloss": "from, away from",                            "pos": "prep", "grammar_note": "governs genitive"},
    "προς":       {"citation": "πρός (+ acc.)",              "gloss": "to, toward, with",                           "pos": "prep", "grammar_note": "most common with accusative"},
    "κατα":       {"citation": "κατά (+ gen. / + acc.)",     "gloss": "against (+ gen.); according to (+ acc.)",    "pos": "prep", "grammar_note": "elides: κατ᾿, καθ᾿"},
    "περι":       {"citation": "περί (+ gen. / + acc.)",     "gloss": "about, concerning (+ gen.); around (+ acc.)","pos": "prep", "grammar_note": "takes genitive or accusative"},
    "μετα":       {"citation": "μετά (+ gen. / + acc.)",     "gloss": "with (+ gen.); after (+ acc.)",              "pos": "prep", "grammar_note": "takes genitive or accusative"},
    "δια":        {"citation": "διά (+ gen. / + acc.)",      "gloss": "through (+ gen.); because of (+ acc.)",      "pos": "prep", "grammar_note": "takes genitive or accusative"},
    "επι":        {"citation": "ἐπί (+ gen. / dat. / acc.)", "gloss": "on, at, over, against",                      "pos": "prep", "grammar_note": "takes all three oblique cases"},
    "παρα":       {"citation": "παρά (+ gen. / dat. / acc.)","gloss": "from (+ gen.); beside (+ dat.); alongside (+ acc.)", "pos": "prep", "grammar_note": "takes all three oblique cases"},
    "υπο":        {"citation": "ὑπό (+ gen. / + acc.)",      "gloss": "by (agent, + gen.); under (+ acc.)",         "pos": "prep", "grammar_note": "gen. for agent, acc. for position"},
    "συν":        {"citation": "σύν (+ dat.)",               "gloss": "with, together with",                        "pos": "prep", "grammar_note": "governs dative"},
    "υπερ":       {"citation": "ὑπέρ (+ gen. / + acc.)",     "gloss": "on behalf of (+ gen.); above (+ acc.)",      "pos": "prep", "grammar_note": "takes genitive or accusative"},
    # Conjunctions & particles
    "και":        {"citation": "καί",                        "gloss": "and, also, even, too",                       "pos": "conj", "grammar_note": "most common NT word; καί … καί = both … and"},
    "δε":         {"citation": "δέ",                         "gloss": "but, and, now (mild contrast or continuation)", "pos": "conj", "grammar_note": "postpositive; never first in clause"},
    "γαρ":        {"citation": "γάρ",                        "gloss": "for, because, indeed (explanatory)",         "pos": "conj", "grammar_note": "postpositive; never first in clause"},
    "αλλα":       {"citation": "ἀλλά",                       "gloss": "but (strong adversative)",                   "pos": "conj", "grammar_note": "coordinating conjunction"},
    "οτι":        {"citation": "ὅτι",                        "gloss": "that (indirect statement); because",         "pos": "conj", "grammar_note": "subordinating conjunction"},
    "ει":         {"citation": "εἰ",                         "gloss": "if (conditional)",                           "pos": "conj", "grammar_note": "εἰ + indicative = simple condition"},
    "ιδου":       {"citation": "ἰδού",                       "gloss": "behold! look! see!",                         "pos": "particle", "grammar_note": "interjection / particle"},
    "ναι":        {"citation": "ναί",                        "gloss": "yes, indeed, certainly",                     "pos": "particle", "grammar_note": "affirmative particle"},
    "ου":         {"citation": "οὐ / οὐκ / οὐχ",            "gloss": "not (negation with indicative)",             "pos": "particle", "grammar_note": "οὐ before consonants, οὐκ before smooth vowels, οὐχ before rough breathing"},
    "μη":         {"citation": "μή",                         "gloss": "not (with non-indicative moods)",            "pos": "particle", "grammar_note": "contrasts with οὐ"},
    "αμην":       {"citation": "ἀμήν",                       "gloss": "truly, verily, amen",                        "pos": "particle", "grammar_note": "Hebrew loanword; ἀμὴν λέγω ὑμῖν = truly I say to you"},
    # Adjectives
    "αγαθος":     {"citation": "ἀγαθός, ἀγαθή, ἀγαθόν",     "gloss": "good (morally good, useful)",                "pos": "adj",  "grammar_note": "1st/2nd declension"},
    "καλος":      {"citation": "καλός, καλή, καλόν",          "gloss": "good, beautiful, fine",                      "pos": "adj",  "grammar_note": "1st/2nd declension; more aesthetic than ἀγαθός"},
    "πιστος":     {"citation": "πιστός, πιστή, πιστόν",       "gloss": "faithful, trustworthy, believing",           "pos": "adj",  "grammar_note": "1st/2nd declension"},
    "αγιος":      {"citation": "ἅγιος, ἁγία, ἅγιον",          "gloss": "holy, set apart, sacred",                    "pos": "adj",  "grammar_note": "1st/2nd declension"},
    "μεγας":      {"citation": "μέγας, μεγάλη, μέγα",         "gloss": "great, large, important",                    "pos": "adj",  "grammar_note": "irregular; gen. μεγάλου"},
    "πας":        {"citation": "πᾶς, πᾶσα, πᾶν",             "gloss": "all, every, whole",                          "pos": "adj",  "grammar_note": "3rd/1st declension (mixed)"},
    "αιωνιος":    {"citation": "αἰώνιος, αἰώνιον",            "gloss": "eternal, everlasting",                       "pos": "adj",  "grammar_note": "2-termination; ζωὴ αἰώνιος = eternal life"},
    "αλλος":      {"citation": "ἄλλος, ἄλλη, ἄλλο",           "gloss": "other, another (of the same kind)",          "pos": "adj",  "grammar_note": "1st/2nd declension; compare ἕτερος"},
    "πολυς":      {"citation": "πολύς, πολλή, πολύ",           "gloss": "many, much, great",                          "pos": "adj",  "grammar_note": "irregular; gen. πολλοῦ, πολλῆς"},
    # Numerals
    "εις_num":    {"citation": "εἷς, μία, ἕν",                "gloss": "one",                                        "pos": "num",  "grammar_note": "irregular numeral; gen. ἑνός, μιᾶς, ἑνός"},
    "δυο":        {"citation": "δύο",                         "gloss": "two",                                        "pos": "num",  "grammar_note": "indeclinable"},
    "τρεις":      {"citation": "τρεῖς, τρία",                 "gloss": "three",                                      "pos": "num",  "grammar_note": "3rd declension numeral"},
}

# ── Lexicon loaders ───────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def _lemmas() -> dict[str, Any]:
    path = _DATA / "grc_lemmas.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text("utf-8"))["entries"]


@lru_cache(maxsize=1)
def _inflections() -> dict[str, str]:
    path = _DATA / "grc_inflections.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text("utf-8"))


@lru_cache(maxsize=1)
def _morph() -> dict[str, dict]:
    """Morphological index: normalised_form → {lemma, pos, case, number, …}."""
    path = _DATA / "grc_morph.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text("utf-8"))["entries"]


def _lookup(key: str) -> dict[str, str] | None:
    """Curated → kaikki lemma → kaikki inflection → None."""
    if key in _CURATED:
        return _CURATED[key]
    lem = _lemmas()
    entry = lem.get(key)
    if entry:
        return entry
    lemma_key = _inflections().get(key)
    if lemma_key:
        return lem.get(lemma_key)
    return None


# ── Morphological feature keys we surface in lesson_data ─────────────────────
_MORPH_FIELDS = ("case", "number", "gender", "tense", "mood", "voice",
                 "person", "aspect", "verbform")

_VERB_POS    = frozenset({"verb", "aux"})
_GRAMMAR_POS = frozenset({"prep", "conj", "particle", "det"})

# ── Unknown-token note ────────────────────────────────────────────────────────

_UNKNOWN_NOTE = (
    "Koine Greek: form not in lexicon or morphological index. "
    "Inflected forms outside the PROIEL/MorphGNT corpus cannot be annotated. "
    "Use CLTK or Morpheus for full morphological parsing."
)

_DICT_ONLY_NOTE = (
    "Koine Greek dictionary mode: lexical entry found but morphological "
    "features not available for this specific inflected form."
)


# ── Plugin ────────────────────────────────────────────────────────────────────

class KoineGreekPlugin:
    language_code = "grc"
    display_name  = "Koine Greek (NT Greek — with morphological annotations)"
    direction     = "ltr"
    capabilities  = LanguageCapabilities(
        code="grc",
        display_name="Koine Greek (NT Greek — with morphological annotations)",
        direction="ltr",
        script_family="greek",
        tokenization_mode="whitespace",
        morphology_depth="shallow",
        lesson_modes_supported=["morphology", "vocabulary", "dictionary"],
        analysis_depth="morphology_light",
        segmentation_quality="medium",
        tokenization_quality="medium",
        morphology_quality="medium",
        syntax_support=False,
        idiom_detection=False,
        tts_lang_tag="el",
        transliteration_scheme="sbl-simplified",
        tense_pool=["present", "imperfect", "aorist", "perfect", "pluperfect", "future"],
        mood_pool=["indicative", "subjunctive", "optative", "imperative", "infinitive", "participle"],
        nuance_capabilities=NuanceCapabilities(
            idioms="none",
            phrase_families="none",
            literary_references="none",
            cultural_references="none",
            etymology="none",
            formality_register="none",
            grammar_nuance="none",
            pronunciation_tts="stub",
            transliteration="partial",
            proverb_tradition="none",
            classical_or_scriptural_allusion="none",
            notes=(
                "Verb forms annotated as conjugation type from PROIEL and MorphGNT "
                "(~13 800 verb forms, covers most of the Greek NT). Prepositions, "
                "conjunctions, and particles emitted as grammar type. "
                "Forms outside these corpora fall back to dictionary mode."
            ),
        ),
    )

    def __init__(self) -> None:
        self.lesson_store: dict[str, CandidateObject] = {}

    def analyze_text(self, text: str) -> list[CandidateSentenceResult]:
        return [self.analyze_sentence(s) for s in self.split_sentences(text)]

    def split_sentences(self, text: str) -> list[str]:
        return [m.group(0).strip() for m in _SENTENCE_RE.finditer(text) if m.group(0).strip()]

    def analyze_sentence(self, sentence: str) -> CandidateSentenceResult:
        candidates: list[CandidateObject] = []
        seen: set[str] = set()

        for raw in sentence.split():
            token = _STRIP_PUNCT.sub("", raw)
            if not token:
                continue
            key = normalize_greek(token)
            if not key or key in seen:
                continue
            seen.add(key)

            romanized   = transliterate(token)
            entry       = _lookup(key)
            morph_entry = _morph().get(key)
            morph_pos   = morph_entry.get("pos") if morph_entry else None

            if morph_pos in _VERB_POS:
                lesson_data: dict[str, Any] = {"surface_form": token, "romanized": romanized}
                if entry:
                    lesson_data["citation_form"] = entry["citation"]
                    lesson_data["gloss"]         = entry["gloss"]
                    lesson_data["grammar_note"]  = entry.get("grammar_note", "")
                for field in _MORPH_FIELDS:
                    if field in morph_entry:
                        lesson_data[field] = morph_entry[field]
                morph_tag = ":".join(
                    f"{f}={morph_entry[f]}" for f in sorted(_MORPH_FIELDS) if f in morph_entry
                )
                candidates.append(CandidateObject(
                    canonical_form=f"{key}:{morph_tag}" if morph_tag else key,
                    surface_form=token,
                    type="conjugation",
                    label=token,
                    lesson_data=lesson_data,
                    confidence=0.80,
                ))

            elif entry is not None:
                pos      = entry["pos"]
                obj_type = "grammar" if pos in _GRAMMAR_POS else "vocabulary"
                lesson_data = {
                    "lemma":         entry["citation"],
                    "citation_form": entry["citation"],
                    "gloss":         entry["gloss"],
                    "grammar_note":  entry.get("grammar_note", ""),
                    "pos":           pos.upper(),
                    "romanized":     romanized,
                }
                if morph_entry:
                    for field in _MORPH_FIELDS:
                        if field in morph_entry:
                            lesson_data[field] = morph_entry[field]
                    confidence: float | None = 0.80
                else:
                    lesson_data["confidence_note"] = _DICT_ONLY_NOTE
                    confidence = 0.70
                candidates.append(CandidateObject(
                    canonical_form=key,
                    surface_form=token,
                    type=obj_type,
                    label=token,
                    lesson_data=lesson_data,
                    confidence=confidence,
                ))

            elif morph_entry:
                lesson_data = {
                    "lemma":           key,
                    "confidence_note": _UNKNOWN_NOTE,
                    "romanized":       romanized,
                }
                for field in _MORPH_FIELDS:
                    if field in morph_entry:
                        lesson_data[field] = morph_entry[field]
                candidates.append(CandidateObject(
                    canonical_form=key,
                    surface_form=token,
                    type="vocabulary",
                    label=token,
                    lesson_data=lesson_data,
                    confidence=0.50,
                ))

            else:
                candidates.append(CandidateObject(
                    canonical_form=key,
                    surface_form=token,
                    type="vocabulary",
                    label=token,
                    lesson_data={
                        "lemma":           key,
                        "confidence_note": _UNKNOWN_NOTE,
                        "romanized":       romanized,
                    },
                    confidence=None,
                ))

        return CandidateSentenceResult(text=sentence, candidates=candidates)

    def get_lesson(self, object_id: str) -> CandidateObject | None:
        return self.lesson_store.get(object_id)


def create_plugin() -> KoineGreekPlugin:
    return KoineGreekPlugin()


# Backward-compat aliases (used by tests written before kaikki integration)
_LEXICON = _CURATED
_normalise = normalize_greek
