"""Latin (Classical) plugin — dictionary-mode with morphological annotations.

BCP-47 code ``"la"``.  Provides whitespace tokenisation backed by:

  1. A compact curated set of ~90 high-priority headwords (always available).
  2. A 65 000-entry Wiktionary-derived lexicon from
     ``data/lexicons/la_lemmas.json`` (generated by ``scripts/ingest_kaikki.py``).
  3. An 828 000-entry inflection table from ``data/lexicons/la_inflections.json``
     that maps normalised inflected forms back to their lemma keys.
  4. A ~257 000-entry morphological index from ``data/lexicons/la_morph.json``
     (~254 000 noun/adj paradigm forms from kaikki.org Wiktionary data plus
     ~3 400 verb/misc forms from the Index Thomisticus Treebank dev split;
     provides case, number, gender, tense, mood, voice, person for annotated
     forms).  Generated by scripts/ingest_kaikki_la_morph.py and
     scripts/ingest_classical_morph.py.

Lookup order per token:
  curated  →  kaikki lemma  →  kaikki inflection  →  unknown.
  Morphological features overlaid from la_morph.json when available.
  Verb forms not in la_morph.json fall back to suffix-rule heuristics;
  noun/adj forms not in la_morph.json fall back to ending-pattern hints.

Sources
────────
  la_morph.json noun/adj data: kaikki_la.jsonl.gz
  (CC BY-SA 3.0 / GFDL, kaikki.org / Wiktionary paradigm tables).
  la_morph.json verb/misc data: la_ittb-ud-dev.conllu
  (Index Thomisticus Treebank, CC BY-NC-SA 3.0, Universal Dependencies).

Known limitations
─────────────────
  Noun/adjective morphological coverage is now broad (~220 000 forms).
  Verb morphological coverage remains limited to the ITTB dev set (~3 400
  forms); irregular and rare verb forms fall back to suffix heuristics.
  Forms outside the annotated corpus fall back to dictionary-mode output.
  No paradigm inference.
"""
from __future__ import annotations

import json
import re
import unicodedata
from functools import lru_cache
from pathlib import Path
from typing import Any

from backend.core.classical_normalize import normalize_latin
from backend.schemas.language import LanguageCapabilities, NuanceCapabilities
from backend.schemas.parse import CandidateObject, CandidateSentenceResult

_DATA = Path(__file__).parents[2] / "data" / "lexicons"

# ── Sentence splitting / token cleaning ──────────────────────────────────────
_SENTENCE_RE = re.compile(r"[^.!?\n]+[.!?\n]?")
_STRIP_PUNCT = re.compile(r"^[.,;:!?()\[\]\"'«»—\-]+|[.,;:!?()\[\]\"'«»—\-]+$")

# ── Curated overrides (take precedence over kaikki for these ~90 entries) ────
# Format: normalized_key → {citation, gloss, pos, grammar_note}

_CURATED: dict[str, dict[str, str]] = {
    # esse
    "sum":      {"citation": "sum, esse, fuī, futūrum",        "gloss": "be, exist",                           "pos": "verb",       "grammar_note": "highly irregular; principal parts: sum, esse, fuī, futūrum"},
    "esse":     {"citation": "sum, esse, fuī, futūrum",        "gloss": "be, exist (infinitive of sum)",       "pos": "verb",       "grammar_note": "present infinitive of sum"},
    # 1st conjugation
    "amo":      {"citation": "amō, amāre, amāvī, amātum",      "gloss": "love, like, be fond of",              "pos": "verb",       "grammar_note": "1st conjugation"},
    "laudo":    {"citation": "laudō, laudāre, laudāvī, laudātum", "gloss": "praise, commend",                  "pos": "verb",       "grammar_note": "1st conjugation"},
    "porto":    {"citation": "portō, portāre, portāvī, portātum", "gloss": "carry, bear, bring",               "pos": "verb",       "grammar_note": "1st conjugation"},
    "voco":     {"citation": "vocō, vocāre, vocāvī, vocātum",  "gloss": "call, summon, name",                  "pos": "verb",       "grammar_note": "1st conjugation"},
    "narro":    {"citation": "narrō, narrāre, narrāvī, narrātum", "gloss": "tell, relate, narrate",            "pos": "verb",       "grammar_note": "1st conjugation"},
    "paro":     {"citation": "parō, parāre, parāvī, parātum",  "gloss": "prepare, obtain",                     "pos": "verb",       "grammar_note": "1st conjugation"},
    "clamo":    {"citation": "clāmō, clāmāre, clāmāvī, clāmātum", "gloss": "shout, cry out",                  "pos": "verb",       "grammar_note": "1st conjugation"},
    "servo":    {"citation": "servō, servāre, servāvī, servātum", "gloss": "save, guard, preserve",            "pos": "verb",       "grammar_note": "1st conjugation"},
    "specto":   {"citation": "spectō, spectāre, spectāvī, spectātum", "gloss": "watch, observe, look at",      "pos": "verb",       "grammar_note": "1st conjugation"},
    # 2nd conjugation
    "video":    {"citation": "videō, vidēre, vīdī, vīsum",     "gloss": "see, look at, understand",            "pos": "verb",       "grammar_note": "2nd conjugation"},
    "habeo":    {"citation": "habeō, habēre, habuī, habitum",  "gloss": "have, hold, consider",                "pos": "verb",       "grammar_note": "2nd conjugation"},
    "moneo":    {"citation": "moneō, monēre, monuī, monitum",  "gloss": "warn, advise, teach",                 "pos": "verb",       "grammar_note": "2nd conjugation"},
    "teneo":    {"citation": "teneō, tenēre, tenuī, tentum",   "gloss": "hold, keep, grasp",                   "pos": "verb",       "grammar_note": "2nd conjugation"},
    "timeo":    {"citation": "timeō, timēre, timuī",           "gloss": "fear, be afraid of",                  "pos": "verb",       "grammar_note": "2nd conjugation (no supine)"},
    "doceo":    {"citation": "doceō, docēre, docuī, doctum",   "gloss": "teach, instruct",                     "pos": "verb",       "grammar_note": "2nd conjugation"},
    "maneo":    {"citation": "maneō, manēre, mānsī, mānsum",   "gloss": "remain, stay, endure",                "pos": "verb",       "grammar_note": "2nd conjugation"},
    # 3rd conjugation
    "lego":     {"citation": "legō, legere, lēgī, lēctum",     "gloss": "read, choose, gather",                "pos": "verb",       "grammar_note": "3rd conjugation"},
    "dico":     {"citation": "dīcō, dīcere, dīxī, dictum",     "gloss": "say, speak, tell",                    "pos": "verb",       "grammar_note": "3rd conjugation"},
    "facio":    {"citation": "faciō, facere, fēcī, factum",    "gloss": "make, do, cause",                     "pos": "verb",       "grammar_note": "3rd conjugation (io-stem)"},
    "pono":     {"citation": "pōnō, pōnere, posuī, positum",   "gloss": "put, place, set down",                "pos": "verb",       "grammar_note": "3rd conjugation"},
    "curro":    {"citation": "currō, currere, cucurrī, cursum", "gloss": "run, hurry",                          "pos": "verb",       "grammar_note": "3rd conjugation"},
    "duco":     {"citation": "dūcō, dūcere, dūxī, ductum",     "gloss": "lead, guide, think",                  "pos": "verb",       "grammar_note": "3rd conjugation"},
    "scribo":   {"citation": "scrībō, scrībere, scrīpsī, scrīptum", "gloss": "write, compose",                 "pos": "verb",       "grammar_note": "3rd conjugation"},
    "mitto":    {"citation": "mittō, mittere, mīsī, missum",   "gloss": "send, let go, throw",                 "pos": "verb",       "grammar_note": "3rd conjugation"},
    "capio":    {"citation": "capiō, capere, cēpī, captum",    "gloss": "take, seize, capture",                "pos": "verb",       "grammar_note": "3rd conjugation (io-stem)"},
    "credo":    {"citation": "crēdō, crēdere, crēdidī, crēditum", "gloss": "believe, trust, entrust",          "pos": "verb",       "grammar_note": "3rd conjugation"},
    # 4th conjugation
    "audio":    {"citation": "audiō, audīre, audīvī, audītum", "gloss": "hear, listen to",                     "pos": "verb",       "grammar_note": "4th conjugation"},
    "venio":    {"citation": "veniō, venīre, vēnī, ventum",    "gloss": "come, arrive",                        "pos": "verb",       "grammar_note": "4th conjugation"},
    "sentio":   {"citation": "sentiō, sentīre, sēnsī, sēnsum", "gloss": "feel, perceive, think",               "pos": "verb",       "grammar_note": "4th conjugation"},
    # 1st declension nouns
    "aqua":     {"citation": "aqua, aquae f.",                 "gloss": "water",                               "pos": "noun",       "grammar_note": "1st declension feminine"},
    "terra":    {"citation": "terra, terrae f.",               "gloss": "land, earth, ground, country",         "pos": "noun",       "grammar_note": "1st declension feminine"},
    "vita":     {"citation": "vīta, vītae f.",                 "gloss": "life",                                "pos": "noun",       "grammar_note": "1st declension feminine"},
    "puella":   {"citation": "puella, puellae f.",             "gloss": "girl",                                "pos": "noun",       "grammar_note": "1st declension feminine"},
    "femina":   {"citation": "fēmina, fēminae f.",             "gloss": "woman",                               "pos": "noun",       "grammar_note": "1st declension feminine"},
    "via":      {"citation": "via, viae f.",                   "gloss": "road, way, path, journey",             "pos": "noun",       "grammar_note": "1st declension feminine"},
    "lingua":   {"citation": "lingua, linguae f.",             "gloss": "language, tongue",                    "pos": "noun",       "grammar_note": "1st declension feminine"},
    "silva":    {"citation": "silva, silvae f.",               "gloss": "forest, woods",                       "pos": "noun",       "grammar_note": "1st declension feminine"},
    "patria":   {"citation": "patria, patriae f.",             "gloss": "homeland, fatherland",                "pos": "noun",       "grammar_note": "1st declension feminine"},
    "luna":     {"citation": "lūna, lūnae f.",                 "gloss": "moon",                                "pos": "noun",       "grammar_note": "1st declension feminine"},
    "gloria":   {"citation": "glōria, glōriae f.",             "gloss": "glory, fame, renown",                 "pos": "noun",       "grammar_note": "1st declension feminine"},
    "porta":    {"citation": "porta, portae f.",               "gloss": "gate, door, entrance",                "pos": "noun",       "grammar_note": "1st declension feminine"},
    "filia":    {"citation": "fīlia, fīliae f.",               "gloss": "daughter",                            "pos": "noun",       "grammar_note": "1st declension feminine"},
    # 2nd declension nouns
    "amicus":   {"citation": "amīcus, amīcī m.",               "gloss": "friend, ally",                        "pos": "noun",       "grammar_note": "2nd declension masculine"},
    "dominus":  {"citation": "dominus, dominī m.",             "gloss": "lord, master, owner",                 "pos": "noun",       "grammar_note": "2nd declension masculine"},
    "filius":   {"citation": "fīlius, fīliī m.",               "gloss": "son",                                 "pos": "noun",       "grammar_note": "2nd declension masculine"},
    "puer":     {"citation": "puer, puerī m.",                 "gloss": "boy, child",                          "pos": "noun",       "grammar_note": "2nd declension masculine (nom. -er)"},
    "servus":   {"citation": "servus, servī m.",               "gloss": "slave, servant",                      "pos": "noun",       "grammar_note": "2nd declension masculine"},
    "vir":      {"citation": "vir, virī m.",                   "gloss": "man, husband, hero",                  "pos": "noun",       "grammar_note": "2nd declension masculine"},
    "deus":     {"citation": "deus, deī m.",                   "gloss": "god, deity",                          "pos": "noun",       "grammar_note": "2nd declension masculine"},
    "bellum":   {"citation": "bellum, bellī n.",               "gloss": "war",                                 "pos": "noun",       "grammar_note": "2nd declension neuter"},
    "verbum":   {"citation": "verbum, verbī n.",               "gloss": "word, verb",                          "pos": "noun",       "grammar_note": "2nd declension neuter"},
    "regnum":   {"citation": "regnum, regnī n.",               "gloss": "kingdom, realm, royal power",         "pos": "noun",       "grammar_note": "2nd declension neuter"},
    "templum":  {"citation": "templum, templī n.",             "gloss": "temple, shrine",                      "pos": "noun",       "grammar_note": "2nd declension neuter"},
    "oppidum":  {"citation": "oppidum, oppidī n.",             "gloss": "town, fortified town",                "pos": "noun",       "grammar_note": "2nd declension neuter"},
    # 3rd declension nouns
    "rex":      {"citation": "rēx, rēgis m.",                  "gloss": "king",                                "pos": "noun",       "grammar_note": "3rd declension masculine"},
    "pax":      {"citation": "pāx, pācis f.",                  "gloss": "peace",                               "pos": "noun",       "grammar_note": "3rd declension feminine"},
    "lex":      {"citation": "lēx, lēgis f.",                  "gloss": "law, rule, statute",                  "pos": "noun",       "grammar_note": "3rd declension feminine"},
    "vox":      {"citation": "vōx, vōcis f.",                  "gloss": "voice, word, sound",                  "pos": "noun",       "grammar_note": "3rd declension feminine"},
    "homo":     {"citation": "homō, hominis m.",               "gloss": "person, human being, man",            "pos": "noun",       "grammar_note": "3rd declension masculine"},
    "amor":     {"citation": "amor, amōris m.",                "gloss": "love, desire, passion",               "pos": "noun",       "grammar_note": "3rd declension masculine"},
    "corpus":   {"citation": "corpus, corporis n.",            "gloss": "body",                                "pos": "noun",       "grammar_note": "3rd declension neuter (s-stem)"},
    "tempus":   {"citation": "tempus, temporis n.",            "gloss": "time, season",                        "pos": "noun",       "grammar_note": "3rd declension neuter (s-stem)"},
    "nomen":    {"citation": "nōmen, nōminis n.",              "gloss": "name, noun",                          "pos": "noun",       "grammar_note": "3rd declension neuter"},
    "urbs":     {"citation": "urbs, urbis f.",                 "gloss": "city",                                "pos": "noun",       "grammar_note": "3rd declension feminine (i-stem)"},
    "mons":     {"citation": "mōns, montis m.",                "gloss": "mountain, hill",                      "pos": "noun",       "grammar_note": "3rd declension masculine (i-stem)"},
    "pater":    {"citation": "pater, patris m.",               "gloss": "father",                              "pos": "noun",       "grammar_note": "3rd declension masculine"},
    "mater":    {"citation": "māter, mātris f.",               "gloss": "mother",                              "pos": "noun",       "grammar_note": "3rd declension feminine"},
    "miles":    {"citation": "mīles, mīlitis m.",              "gloss": "soldier",                             "pos": "noun",       "grammar_note": "3rd declension masculine"},
    "caput":    {"citation": "caput, capitis n.",              "gloss": "head, leader, source",                "pos": "noun",       "grammar_note": "3rd declension neuter"},
    "dux":      {"citation": "dux, ducis m.",                  "gloss": "leader, general, guide",              "pos": "noun",       "grammar_note": "3rd declension masculine"},
    # Adjectives
    "bonus":    {"citation": "bonus, bona, bonum",             "gloss": "good, kind, brave",                   "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "malus":    {"citation": "malus, mala, malum",             "gloss": "bad, evil, wicked",                   "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "magnus":   {"citation": "magnus, magna, magnum",          "gloss": "great, large, important",             "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "parvus":   {"citation": "parvus, parva, parvum",          "gloss": "small, little",                       "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "multus":   {"citation": "multus, multa, multum",          "gloss": "much, many",                          "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "novus":    {"citation": "novus, nova, novum",             "gloss": "new, young, fresh",                   "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "longus":   {"citation": "longus, longa, longum",          "gloss": "long, tall, far",                     "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "altus":    {"citation": "altus, alta, altum",             "gloss": "high, deep, tall",                    "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "sanctus":  {"citation": "sānctus, sāncta, sānctum",       "gloss": "holy, sacred, venerable",             "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "antiquus": {"citation": "antīquus, antīqua, antīquum",    "gloss": "ancient, old, former",                "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "clarus":   {"citation": "clārus, clāra, clārum",          "gloss": "clear, bright, famous",               "pos": "adj",        "grammar_note": "1st/2nd declension"},
    "liber":    {"citation": "līber, lībera, līberum",         "gloss": "free, unrestricted",                  "pos": "adj",        "grammar_note": "1st/2nd declension (nom. -er)"},
    "pulcher":  {"citation": "pulcher, pulchra, pulchrum",      "gloss": "beautiful, handsome, fine",           "pos": "adj",        "grammar_note": "1st/2nd declension (nom. -er)"},
    # Pronouns
    "ego":      {"citation": "ego (nōs)",                      "gloss": "I, me",                               "pos": "pron",       "grammar_note": "1st person singular; plural nōs"},
    "tu":       {"citation": "tū (vōs)",                       "gloss": "you (singular)",                      "pos": "pron",       "grammar_note": "2nd person singular; plural vōs"},
    "nos":      {"citation": "nōs",                            "gloss": "we, us",                              "pos": "pron",       "grammar_note": "1st person plural"},
    "vos":      {"citation": "vōs",                            "gloss": "you, you all (plural)",               "pos": "pron",       "grammar_note": "2nd person plural"},
    # Prepositions
    "in":       {"citation": "in (+ abl. / + acc.)",           "gloss": "in, on (+ abl.); into, onto (+ acc.)", "pos": "prep",      "grammar_note": "+ ablative for location, + accusative for motion"},
    "ad":       {"citation": "ad (+ acc.)",                    "gloss": "to, toward, near, at",                "pos": "prep",       "grammar_note": "governs accusative"},
    "cum":      {"citation": "cum (+ abl.)",                   "gloss": "with, together with",                 "pos": "prep",       "grammar_note": "governs ablative"},
    "per":      {"citation": "per (+ acc.)",                   "gloss": "through, by means of, during",        "pos": "prep",       "grammar_note": "governs accusative"},
    "ex":       {"citation": "ex / ē (+ abl.)",                "gloss": "out of, from, since",                 "pos": "prep",       "grammar_note": "governs ablative; ex before consonants, ē before vowels"},
    "de":       {"citation": "dē (+ abl.)",                    "gloss": "about, concerning, from",             "pos": "prep",       "grammar_note": "governs ablative"},
    "sub":      {"citation": "sub (+ abl. / + acc.)",          "gloss": "under (+ abl.); up to (+ acc.)",      "pos": "prep",       "grammar_note": "+ ablative for rest, + accusative for motion"},
    "ante":     {"citation": "ante (+ acc.)",                  "gloss": "before, in front of",                 "pos": "prep",       "grammar_note": "governs accusative"},
    "post":     {"citation": "post (+ acc.)",                  "gloss": "after, behind, later than",           "pos": "prep",       "grammar_note": "governs accusative"},
    "sine":     {"citation": "sine (+ abl.)",                  "gloss": "without",                             "pos": "prep",       "grammar_note": "governs ablative"},
    "pro":      {"citation": "prō (+ abl.)",                   "gloss": "for, on behalf of, in front of",      "pos": "prep",       "grammar_note": "governs ablative"},
    "ab":       {"citation": "ab / ā (+ abl.)",                "gloss": "from, away from, by (agent)",         "pos": "prep",       "grammar_note": "governs ablative; ab before vowels/h"},
    # Conjunctions & adverbs
    "et":       {"citation": "et",                             "gloss": "and, also, even",                     "pos": "conj",       "grammar_note": "coordinating conjunction"},
    "sed":      {"citation": "sed",                            "gloss": "but, however, yet",                   "pos": "conj",       "grammar_note": "adversative conjunction"},
    "aut":      {"citation": "aut",                            "gloss": "or, either",                          "pos": "conj",       "grammar_note": "disjunctive conjunction"},
    "non":      {"citation": "nōn",                            "gloss": "not",                                 "pos": "adv",        "grammar_note": "negation adverb"},
    "iam":      {"citation": "iam",                            "gloss": "now, already, soon",                  "pos": "adv",        "grammar_note": "temporal adverb"},
    "sic":      {"citation": "sīc",                            "gloss": "thus, so, in this way",               "pos": "adv",        "grammar_note": "demonstrative adverb"},
    "nec":      {"citation": "nec / neque",                    "gloss": "and not, nor, neither",               "pos": "conj",       "grammar_note": "negative copulative conjunction"},
    "neque":    {"citation": "neque / nec",                    "gloss": "nor, and not",                        "pos": "conj",       "grammar_note": "negative copulative conjunction"},
    "nam":      {"citation": "nam",                            "gloss": "for, because, indeed",                "pos": "conj",       "grammar_note": "causal/explanatory particle"},
    "ubi":      {"citation": "ubi",                            "gloss": "where, when",                         "pos": "adv",        "grammar_note": "relative/interrogative adverb"},
    "nunc":     {"citation": "nunc",                           "gloss": "now, at present",                     "pos": "adv",        "grammar_note": "temporal adverb"},
    "tum":      {"citation": "tum / tunc",                     "gloss": "then, at that time",                  "pos": "adv",        "grammar_note": "temporal adverb"},
    "tunc":     {"citation": "tunc / tum",                     "gloss": "then, at that time",                  "pos": "adv",        "grammar_note": "temporal adverb"},
    "semper":   {"citation": "semper",                         "gloss": "always, ever",                        "pos": "adv",        "grammar_note": "temporal adverb"},
    "saepe":    {"citation": "saepe",                          "gloss": "often, frequently",                   "pos": "adv",        "grammar_note": "temporal adverb"},
    "numquam":  {"citation": "numquam",                        "gloss": "never",                               "pos": "adv",        "grammar_note": "negative temporal adverb"},
    "si":       {"citation": "sī",                             "gloss": "if, in case that",                    "pos": "conj",       "grammar_note": "conditional conjunction"},
    "ut":       {"citation": "ut",                             "gloss": "as, when, in order that, that",       "pos": "conj",       "grammar_note": "final / consecutive / temporal / comparative"},
    "quod":     {"citation": "quod",                           "gloss": "because, that, the fact that",        "pos": "conj",       "grammar_note": "causal/substantive; also neut. of quī"},
    "ergo":     {"citation": "ergō",                           "gloss": "therefore, consequently",             "pos": "adv",        "grammar_note": "inferential adverb/conjunction"},
    # Numerals
    "unus":     {"citation": "ūnus, ūna, ūnum",                "gloss": "one",                                 "pos": "num",        "grammar_note": "irregular gen. -īus, dat. -ī"},
    "duo":      {"citation": "duo, duae, duo",                 "gloss": "two",                                 "pos": "num",        "grammar_note": "irregular declension"},
    "tres":     {"citation": "trēs, tria",                     "gloss": "three",                               "pos": "num",        "grammar_note": "3rd declension"},
    "decem":    {"citation": "decem",                          "gloss": "ten",                                 "pos": "num",        "grammar_note": "indeclinable"},
    "centum":   {"citation": "centum",                         "gloss": "one hundred",                         "pos": "num",        "grammar_note": "indeclinable"},
    "mille":    {"citation": "mīlle (pl. mīlia, mīlium)",      "gloss": "one thousand",                        "pos": "num",        "grammar_note": "singular indeclinable; plural mīlia is 3rd decl. neuter noun"},
}

# ── Lexicon loaders ───────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def _lemmas() -> dict[str, Any]:
    path = _DATA / "la_lemmas.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text("utf-8"))["entries"]


@lru_cache(maxsize=1)
def _inflections() -> dict[str, str]:
    path = _DATA / "la_inflections.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text("utf-8"))


@lru_cache(maxsize=1)
def _morph() -> dict[str, dict]:
    """Morphological index: normalised_form → {lemma, pos, case, number, …}."""
    path = _DATA / "la_morph.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text("utf-8"))["entries"]


def _lookup(key: str) -> dict[str, str] | None:
    """Curated → kaikki lemma → kaikki inflection → None."""
    if key in _CURATED:
        return _CURATED[key]
    lem = _lemmas()
    entry = lem.get(key)
    if entry:
        return entry
    lemma_key = _inflections().get(key)
    if lemma_key:
        return lem.get(lemma_key)
    return None


# ── Morphological feature keys surfaced in lesson_data ───────────────────────
_MORPH_FIELDS = ("case", "number", "gender", "tense", "mood", "voice",
                 "person", "aspect", "verbform")

# ── Unknown-token notes ───────────────────────────────────────────────────────

_UNKNOWN_NOTE = (
    "Latin: form not in lexicon or morphological index. "
    "Use CLTK or Whitaker's Words for full morphological parsing."
)

_DICT_ONLY_NOTE = (
    "Latin: lexical entry found but morphological features not available "
    "for this specific inflected form (verb form not in morph index)."
)

_SUFFIX_NOTE = (
    "Latin suffix-based: outermost ending matched against imperfect/future/infinitive "
    "patterns. Accuracy is moderate; consult Whitaker's Words or CLTK for definitive analysis."
)

_VERB_POS    = frozenset({"verb", "aux"})
_GRAMMAR_POS = frozenset({"prep", "conj", "particle", "det"})

# Imperfect and future active for 1st/2nd conjugation are highly distinctive.
# Infinitives (-are/-ere/-ire) require at least one stem char before the suffix.
_LATIN_VERB_SUFFIXES: list[tuple[str, dict]] = [
    ("abatis", {"tense": "imperfect", "voice": "active", "person": "second", "number": "plural",   "verbform": "finite"}),
    ("ebatis", {"tense": "imperfect", "voice": "active", "person": "second", "number": "plural",   "verbform": "finite"}),
    ("abamus", {"tense": "imperfect", "voice": "active", "person": "first",  "number": "plural",   "verbform": "finite"}),
    ("ebamus", {"tense": "imperfect", "voice": "active", "person": "first",  "number": "plural",   "verbform": "finite"}),
    ("abant",  {"tense": "imperfect", "voice": "active", "person": "third",  "number": "plural",   "verbform": "finite"}),
    ("ebant",  {"tense": "imperfect", "voice": "active", "person": "third",  "number": "plural",   "verbform": "finite"}),
    ("abat",   {"tense": "imperfect", "voice": "active", "person": "third",  "number": "singular", "verbform": "finite"}),
    ("ebat",   {"tense": "imperfect", "voice": "active", "person": "third",  "number": "singular", "verbform": "finite"}),
    ("abas",   {"tense": "imperfect", "voice": "active", "person": "second", "number": "singular", "verbform": "finite"}),
    ("ebas",   {"tense": "imperfect", "voice": "active", "person": "second", "number": "singular", "verbform": "finite"}),
    ("abam",   {"tense": "imperfect", "voice": "active", "person": "first",  "number": "singular", "verbform": "finite"}),
    ("ebam",   {"tense": "imperfect", "voice": "active", "person": "first",  "number": "singular", "verbform": "finite"}),
    ("abitis", {"tense": "future",    "voice": "active", "person": "second", "number": "plural",   "verbform": "finite"}),
    ("ebitis", {"tense": "future",    "voice": "active", "person": "second", "number": "plural",   "verbform": "finite"}),
    ("abimus", {"tense": "future",    "voice": "active", "person": "first",  "number": "plural",   "verbform": "finite"}),
    ("ebimus", {"tense": "future",    "voice": "active", "person": "first",  "number": "plural",   "verbform": "finite"}),
    ("abunt",  {"tense": "future",    "voice": "active", "person": "third",  "number": "plural",   "verbform": "finite"}),
    ("ebunt",  {"tense": "future",    "voice": "active", "person": "third",  "number": "plural",   "verbform": "finite"}),
    ("abit",   {"tense": "future",    "voice": "active", "person": "third",  "number": "singular", "verbform": "finite"}),
    ("ebit",   {"tense": "future",    "voice": "active", "person": "third",  "number": "singular", "verbform": "finite"}),
    ("abis",   {"tense": "future",    "voice": "active", "person": "second", "number": "singular", "verbform": "finite"}),
    ("ebis",   {"tense": "future",    "voice": "active", "person": "second", "number": "singular", "verbform": "finite"}),
    ("abo",    {"tense": "future",    "voice": "active", "person": "first",  "number": "singular", "verbform": "finite"}),
    ("ebo",    {"tense": "future",    "voice": "active", "person": "first",  "number": "singular", "verbform": "finite"}),
    ("isse",   {"tense": "perfect",   "voice": "active", "verbform": "infinitive"}),
    ("are",    {"tense": "present",   "voice": "active", "verbform": "infinitive"}),
    ("ere",    {"tense": "present",   "voice": "active", "verbform": "infinitive"}),
    ("ire",    {"tense": "present",   "voice": "active", "verbform": "infinitive"}),
]


def _extract_latin_verb_morph(key: str) -> dict | None:
    for suffix, features in _LATIN_VERB_SUFFIXES:
        if key.endswith(suffix) and len(key) > len(suffix):
            return dict(features)
    return None


# ── Noun / adjective suffix hints ────────────────────────────────────────────
# Used when a form is not in the morph index to give case/number/gender hints.
# Listed longest-match first. Confidence is intentionally low (heuristic only).
# Many Latin forms are ambiguous across multiple cases; ambiguous_note is set
# where two or more common case interpretations share the same ending.
_LATIN_NOUN_SUFFIXES: list[tuple[str, dict, str | None]] = [
    # (suffix, features, ambiguous_note or None)
    # Longest suffixes first to prevent shorter rules from shadowing them.
    # 1st–2nd declension genitive plural (-arum, -orum)
    ("arum",  {"case": "genitive",  "number": "plural",   "gender": "feminine"},  None),
    ("orum",  {"case": "genitive",  "number": "plural"},   None),
    # 3rd declension dative/ablative plural (-ibus) — before -us/-is
    ("ibus",  {"case": "dative_or_ablative", "number": "plural"}, "Ambiguous: dat pl / abl pl"),
    # 1st declension genitive/dative singular and plural (-ae)
    ("ae",    {"case": "genitive_or_dative_or_nominative_plural", "number": "singular_or_plural", "gender": "feminine"}, "Ambiguous: gen sg / dat sg / nom pl for 1st decl nouns"),
    # Genitive singular / nominative-vocative plural (-is)
    ("is",    {"case": "genitive_or_dative", "number": "singular"}, "Ambiguous: genitive sg (1st/2nd decl) or nominative/vocative pl (3rd decl)"),
    # Accusative plural feminine (-as), accusative singular feminine (-am)
    ("as",    {"case": "accusative", "number": "plural",   "gender": "feminine"},  None),
    ("am",    {"case": "accusative", "number": "singular", "gender": "feminine"},  None),
    # 2nd declension accusative plural masculine (-os), accusative/genitive/neuter (-um)
    ("os",    {"case": "accusative", "number": "plural",   "gender": "masculine"}, None),
    ("um",    {"case": "accusative_or_genitive_plural_or_nominative_neuter", "number": "singular_or_plural"}, "Ambiguous: acc sg masc, gen pl (2nd decl), nom/acc sg neut"),
    # 3rd declension accusative singular (-em), nom/acc plural (-es)
    ("em",    {"case": "accusative", "number": "singular"}, None),
    ("es",    {"case": "nominative_or_accusative", "number": "plural"}, "Ambiguous: nom pl / acc pl (3rd decl i-stem)"),
    # 2nd declension nominative singular masculine (-us) — after -ibus
    ("us",    {"case": "nominative", "number": "singular", "gender": "masculine"}, None),
    # 2nd declension genitive sg / nominative plural (-i)
    ("i",     {"case": "genitive_or_nominative_plural", "number": "singular_or_plural", "gender": "masculine"}, "Ambiguous: gen sg (2nd decl) or nom pl (2nd decl)"),
    # Short vowel endings — last (most ambiguous)
    ("a",     {"case": "ablative_or_nominative", "number": "singular"}, "Ambiguous: ablative sg / nominative sg (1st decl)"),
    ("o",     {"case": "dative_or_ablative", "number": "singular"}, "Ambiguous: dat sg / abl sg (2nd decl)"),
]

_NOUN_SUFFIX_NOTE = (
    "Latin noun suffix hint (heuristic): case/number assignment is probable based on "
    "ending pattern only. Latin has significant case syncretism; consult a full "
    "morphological parser (CLTK, Whitaker's Words) for definitive analysis."
)


def _extract_latin_noun_suffix_hint(key: str) -> tuple[dict, str | None] | None:
    """Return (features, ambiguous_note) for a Latin noun suffix, or None."""
    for suffix, features, amb_note in _LATIN_NOUN_SUFFIXES:
        if key.endswith(suffix) and len(key) > len(suffix) + 1:
            return dict(features), amb_note
    return None


# ── Plugin ────────────────────────────────────────────────────────────────────

class LatinPlugin:
    language_code = "la"
    display_name  = "Latin (Classical — with morphological annotations)"
    direction     = "ltr"
    capabilities  = LanguageCapabilities(
        code="la",
        display_name="Latin (Classical — with morphological annotations)",
        direction="ltr",
        script_family="latin",
        tokenization_mode="whitespace",
        morphology_depth="shallow",
        lesson_modes_supported=["morphology", "vocabulary", "dictionary"],
        analysis_depth="morphology_light",
        segmentation_quality="medium",
        tokenization_quality="medium",
        morphology_quality="medium",
        syntax_support=False,
        idiom_detection=False,
        tts_lang_tag="la",
        transliteration_scheme=None,
        tense_pool=["present", "imperfect", "perfect", "pluperfect", "future", "future_perfect"],
        mood_pool=["indicative", "subjunctive", "imperative", "infinitive", "participle"],
        nuance_capabilities=NuanceCapabilities(
            idioms="none",
            phrase_families="none",
            literary_references="none",
            cultural_references="none",
            etymology="none",
            formality_register="none",
            grammar_nuance="none",
            pronunciation_tts="stub",
            transliteration="none",
            proverb_tradition="none",
            classical_or_scriptural_allusion="none",
            notes=(
                "Verb forms annotated as conjugation type when found in ITTB morph index "
                "(~3 400 forms). Imperfect/future active and infinitive endings also "
                "detected via suffix rules with moderate confidence. Prepositions, "
                "conjunctions, and particles emitted as grammar type. "
                "Forms outside ITTB fall back to suffix or dictionary mode."
            ),
        ),
    )

    def __init__(self) -> None:
        self.lesson_store: dict[str, CandidateObject] = {}

    def analyze_text(self, text: str) -> list[CandidateSentenceResult]:
        return [self.analyze_sentence(s) for s in self.split_sentences(text)]

    def split_sentences(self, text: str) -> list[str]:
        return [m.group(0).strip() for m in _SENTENCE_RE.finditer(text) if m.group(0).strip()]

    def analyze_sentence(self, sentence: str) -> CandidateSentenceResult:
        candidates: list[CandidateObject] = []
        seen: set[str] = set()

        for raw in sentence.split():
            token = _STRIP_PUNCT.sub("", raw)
            if not token:
                continue
            key = normalize_latin(token)
            if not key or key in seen:
                continue
            seen.add(key)

            entry       = _lookup(key)
            morph_entry = _morph().get(key)
            morph_pos   = morph_entry.get("pos") if morph_entry else None
            # Distinguish citation-form hits from inflection-resolved hits.
            is_lemma = (key in _CURATED) or (key in _lemmas())

            if morph_pos in _VERB_POS:
                lesson_data: dict[str, Any] = {"surface_form": token}
                if entry:
                    lesson_data["citation_form"] = entry["citation"]
                    lesson_data["gloss"]         = entry["gloss"]
                    lesson_data["grammar_note"]  = entry.get("grammar_note", "")
                for field in _MORPH_FIELDS:
                    if field in morph_entry:
                        lesson_data[field] = morph_entry[field]
                morph_tag = ":".join(
                    f"{f}={morph_entry[f]}" for f in sorted(_MORPH_FIELDS) if f in morph_entry
                )
                candidates.append(CandidateObject(
                    canonical_form=f"{key}:{morph_tag}" if morph_tag else key,
                    surface_form=token,
                    type="conjugation",
                    label=token,
                    lesson_data=lesson_data,
                    confidence=0.80,
                ))

            elif entry is not None and is_lemma:
                pos      = entry["pos"]
                obj_type = "grammar" if pos in _GRAMMAR_POS else "vocabulary"
                lesson_data = {
                    "lemma":         entry["citation"],
                    "citation_form": entry["citation"],
                    "gloss":         entry["gloss"],
                    "grammar_note":  entry.get("grammar_note", ""),
                    "pos":           pos.upper(),
                }
                if morph_entry:
                    for field in _MORPH_FIELDS:
                        if field in morph_entry:
                            lesson_data[field] = morph_entry[field]
                    confidence: float | None = 0.80
                else:
                    lesson_data["confidence_note"] = _DICT_ONLY_NOTE
                    confidence = 0.70
                candidates.append(CandidateObject(
                    canonical_form=key,
                    surface_form=token,
                    type=obj_type,
                    label=token,
                    lesson_data=lesson_data,
                    confidence=confidence,
                ))

            elif entry is not None and not is_lemma and entry["pos"] == "verb":
                # Inflection-resolved verb: only emit conjugation if we have
                # tense+mood (C9 contract).  Suffix rules cover imperfect/future/
                # infinitives; forms without a match fall back to vocabulary.
                verb_morph = _extract_latin_verb_morph(key)
                lesson_data = {
                    "citation_form": entry["citation"],
                    "gloss":         entry["gloss"],
                    "grammar_note":  entry.get("grammar_note", ""),
                    "surface_form":  token,
                }
                if verb_morph:
                    lesson_data.update(verb_morph)
                    lesson_data["confidence_note"] = _SUFFIX_NOTE
                    morph_tag = ":".join(f"{k}={v}" for k, v in sorted(verb_morph.items()))
                    candidates.append(CandidateObject(
                        canonical_form=f"{key}:{morph_tag}",
                        surface_form=token,
                        type="conjugation",
                        label=token,
                        lesson_data=lesson_data,
                        confidence=0.55,
                    ))
                else:
                    lesson_data["lemma"]           = entry["citation"]
                    lesson_data["confidence_note"] = _DICT_ONLY_NOTE
                    candidates.append(CandidateObject(
                        canonical_form=key,
                        surface_form=token,
                        type="vocabulary",
                        label=token,
                        lesson_data=lesson_data,
                        confidence=0.50,
                    ))

            elif entry is not None:
                # Inflection-resolved non-verb (noun/adj/etc.)
                pos      = entry["pos"]
                obj_type = "grammar" if pos in _GRAMMAR_POS else "vocabulary"
                lesson_data = {
                    "lemma":         entry["citation"],
                    "citation_form": entry["citation"],
                    "gloss":         entry["gloss"],
                    "grammar_note":  entry.get("grammar_note", ""),
                    "pos":           pos.upper(),
                    "confidence_note": _DICT_ONLY_NOTE,
                }
                if morph_entry:
                    for field in _MORPH_FIELDS:
                        if field in morph_entry:
                            lesson_data[field] = morph_entry[field]
                    confidence = 0.70
                else:
                    # No morph entry — add noun suffix hint if applicable
                    noun_hint = _extract_latin_noun_suffix_hint(key)
                    if noun_hint:
                        hint_feats, amb_note = noun_hint
                        if "case" in hint_feats and "case" not in lesson_data:
                            lesson_data["case_hint"]   = hint_feats["case"]
                        if "number" in hint_feats and "number" not in lesson_data:
                            lesson_data["number_hint"] = hint_feats["number"]
                        if "gender" in hint_feats and "gender" not in lesson_data:
                            lesson_data["gender_hint"] = hint_feats["gender"]
                        if amb_note:
                            lesson_data["ambiguity_note"] = amb_note
                        lesson_data["confidence_note"] = _NOUN_SUFFIX_NOTE
                    confidence = 0.60
                candidates.append(CandidateObject(
                    canonical_form=key,
                    surface_form=token,
                    type=obj_type,
                    label=token,
                    lesson_data=lesson_data,
                    confidence=confidence,
                ))

            elif morph_entry:
                lesson_data = {"lemma": key, "confidence_note": _UNKNOWN_NOTE}
                for field in _MORPH_FIELDS:
                    if field in morph_entry:
                        lesson_data[field] = morph_entry[field]
                candidates.append(CandidateObject(
                    canonical_form=key,
                    surface_form=token,
                    type="vocabulary",
                    label=token,
                    lesson_data=lesson_data,
                    confidence=0.50,
                ))

            else:
                lesson_data = {"lemma": key, "confidence_note": _UNKNOWN_NOTE}
                noun_hint = _extract_latin_noun_suffix_hint(key)
                if noun_hint:
                    hint_feats, amb_note = noun_hint
                    if "case" in hint_feats:
                        lesson_data["case_hint"]   = hint_feats["case"]
                    if "number" in hint_feats:
                        lesson_data["number_hint"] = hint_feats["number"]
                    if "gender" in hint_feats:
                        lesson_data["gender_hint"] = hint_feats["gender"]
                    if amb_note:
                        lesson_data["ambiguity_note"] = amb_note
                    lesson_data["confidence_note"] = _NOUN_SUFFIX_NOTE
                candidates.append(CandidateObject(
                    canonical_form=key,
                    surface_form=token,
                    type="vocabulary",
                    label=token,
                    lesson_data=lesson_data,
                    confidence=None,
                ))

        return CandidateSentenceResult(text=sentence, candidates=candidates)

    def get_lesson(self, object_id: str) -> CandidateObject | None:
        return self.lesson_store.get(object_id)


def create_plugin() -> LatinPlugin:
    return LatinPlugin()


# Backward-compat aliases (used by tests written before kaikki integration)
_LEXICON = _CURATED
_normalise = normalize_latin
