"""Generate and insert Russian verbal government entries from a JSON spec file.

Usage:
    python scripts/gen_verbal_government.py [--dry-run] [--validate-only]

The JSON spec file lives at scripts/data/ru_verbal_government.json and contains
a list of objects with this schema:

    {
      "lemma": "желать",
      "case": "genitive",
      "example": "«желать» governs the genitive: желать успеха (to wish success)"
    }

Valid case strings:
    nominative, genitive, dative, accusative, instrumental, prepositional,
    accusative/genitive, dative/accusative, genitive/accusative,
    accusative+dative, prepositional+о

The script:
  1. Loads and validates the spec file.
  2. Reads existing lemmas from _VERBAL_GOV in backend/nuance/ru.py.
  3. Skips any lemma already present (idempotent).
  4. Generates Python dict entries and inserts them before the closing '}'
     of _VERBAL_GOV.
  5. Reports counts.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = Path(__file__).resolve().parent / "data"
TARGET = ROOT / "backend" / "nuance" / "ru.py"
SPEC_FILE = DATA_DIR / "ru_verbal_government.json"

VALID_CASES = {
    "nominative", "genitive", "dative", "accusative",
    "instrumental", "prepositional",
    "accusative/genitive", "genitive/accusative",
    "dative/accusative", "accusative/dative",
    "accusative+dative", "prepositional+о",
    "genitive+dative",
}


def _existing_lemmas() -> set[str]:
    src = TARGET.read_text(encoding="utf-8")
    return set(re.findall(r'"([\wЀ-ӿ]+)"\s*:\s*\(', src))


def _load_spec() -> list[dict]:
    if not SPEC_FILE.exists():
        sys.exit(f"[error] spec file not found: {SPEC_FILE}")
    with SPEC_FILE.open(encoding="utf-8") as f:
        return json.load(f)


def _validate(specs: list[dict], existing: set[str]) -> tuple[list[dict], list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    seen: set[str] = set()
    valid: list[dict] = []

    for entry in specs:
        lemma = entry.get("lemma", "").strip()
        case = entry.get("case", "").strip()
        example = entry.get("example", "").strip()

        if not lemma:
            errors.append("  entry missing 'lemma' field")
            continue
        if not case:
            errors.append(f"  [{lemma}] missing 'case' field")
        elif case not in VALID_CASES:
            errors.append(f"  [{lemma}] invalid case {case!r}; must be one of {sorted(VALID_CASES)}")
        if not example:
            errors.append(f"  [{lemma}] missing 'example' field")
        if lemma in existing:
            warnings.append(f"  [{lemma}] already in _VERBAL_GOV — skipping")
            continue
        if lemma in seen:
            errors.append(f"  [{lemma}] duplicate lemma in spec file")
            continue
        seen.add(lemma)

        if not errors:
            valid.append(entry)

    return valid, errors, warnings


def _render_entry(entry: dict) -> str:
    lemma = entry["lemma"]
    case = entry["case"]
    example = entry["example"].replace('"', '\\"')
    return f'    {lemma!r}: ({case!r}, "{example}"),'


def _patch_file(new_entries: list[dict], dry_run: bool) -> int:
    src = TARGET.read_text(encoding="utf-8")

    # Locate closing '}' of _VERBAL_GOV: the dict ends at the first
    # standalone '}' after the _VERBAL_GOV assignment.
    match = re.search(r'(_VERBAL_GOV[^{]*\{)', src)
    if not match:
        sys.exit("[error] cannot locate _VERBAL_GOV in ru.py")

    dict_start = match.end()
    # Find matching closing brace
    depth = 1
    pos = dict_start
    while pos < len(src) and depth:
        if src[pos] == '{':
            depth += 1
        elif src[pos] == '}':
            depth -= 1
        pos += 1
    close_pos = pos - 1  # position of the closing '}'

    code_lines = ["\n    # ── generated by gen_verbal_government.py ──"]
    for entry in new_entries:
        code_lines.append(_render_entry(entry))

    insertion = "\n".join(code_lines) + "\n"

    new_src = src[:close_pos] + insertion + src[close_pos:]

    if dry_run:
        print("[dry-run] would insert:")
        print(insertion[:2000])
        if len(insertion) > 2000:
            print(f"  ... ({len(insertion) - 2000} more chars)")
        return len(new_entries)

    TARGET.write_text(new_src, encoding="utf-8")
    return len(new_entries)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate RU verbal government entries")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print generated code without modifying ru.py")
    parser.add_argument("--validate-only", action="store_true",
                        help="Validate spec without generating code")
    args = parser.parse_args()

    existing = _existing_lemmas()
    print(f"Existing _VERBAL_GOV: {len(existing)} lemmas")

    specs = _load_spec()
    valid, errors, warnings = _validate(specs, existing)

    for w in warnings:
        print(f"[warn]  {w}")
    if errors:
        print(f"[ERROR] {len(errors)} validation error(s):")
        for e in errors:
            print(e)
        sys.exit(f"\n{len(errors)} error(s). Aborting.")

    print(f"[ok]    {len(valid)} new entries validated")

    if args.validate_only:
        print("\nValidation passed. (--validate-only: no files written)")
        return

    n = _patch_file(valid, dry_run=args.dry_run)

    if args.dry_run:
        print(f"\n[dry-run] {n} entries would be added.")
        return

    print(f"[wrote] {n} entries appended to backend/nuance/ru.py")

    # Verify by importing
    import subprocess
    result = subprocess.run(
        [sys.executable, "-c",
         "from backend.nuance.ru import _VERBAL_GOV; "
         "print(f'_VERBAL_GOV size: {len(_VERBAL_GOV)}')"],
        capture_output=True, text=True, cwd=str(ROOT)
    )
    if result.returncode != 0:
        print("[ERROR] import failed:")
        print(result.stderr)
        sys.exit(1)
    print(result.stdout.strip())
    print(f"\nDone. {n} new verbal government entries added.")


if __name__ == "__main__":
    main()
